name: thenounproject
description: thenounproject
version: 0.0.1
homepage: https://github.com/justkawal

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  oauth2: ^2.0.0
  #equatable: ^2.0.0

dev_dependencies:
  #test: ^1.16.5